version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ZvjaWvGcsrxQTbcDHVpU3bW89cDKamDF
    volumes: 
      - cache:/data
  api:
    container_name: bridges-api
    build: ./api
    image: bridges-api
    depends_on:
      - cache
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: ZvjaWvGcsrxQTbcDHVpU3bW89cDKamDF
    links:
      - db
    volumes:
      - ./api:/app
volumes:
  cache:
    driver: local