pools:
  known:
    features:
      - feature: check_known
        value: true
      - feature: is_working_hours
        value: true
    bridges:
      - known_1
      - known_2
      - known_3
      - known_4
  suspicious:
    features:
      - feature: is_working_hours
        value: false
    bridges:
      - suspicious_1
      - suspicious_2
      - suspicious_3
      - suspicious_4
  quarantine:
    features:
      - feature: check_known
        value: false
      - feature: is_russian
        value: true
      - feature: is_working_hours
        value: true
    bridges:
      - quarantine_1
      - quarantine_2
      - quarantine_3
      - quarantine_4
      - quarantine_5
      - quarantine_6
      - quarantine_7
      - quarantine_8
